/**
 * Merchant.js — merchant risk profiles.
 *
 * Every merchant that appears in a transaction gets a profile with:
 *   - MCC (Merchant Category Code) — standard 4-digit code
 *   - Risk tier (low / medium / high / critical) derived from dispute rate,
 *     average fraud score, and volume anomalies
 *   - Dispute rate (rolling 30-day disputes / transactions)
 *   - Volume analytics (total transactions, total amount, unique customers)
 *   - Fraud rate (flagged / total)
 */
const mongoose = require('mongoose');

const merchantSchema = new mongoose.Schema({
  merchantId:   { type: String, required: true, unique: true, index: true },
  name:         { type: String },           // human-readable name (optional)
  mcc:          { type: String },           // 4-digit MCC code
  mccCategory:  { type: String },           // derived from MCC lookup
  country:      { type: String, default: 'IN' },

  // ── Risk tiering ──────────────────────────────────────────
  riskTier: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'low',
    index: true,
  },
  riskScore:    { type: Number, default: 0, min: 0, max: 100 },

  // ── Dispute metrics (rolling 30-day window) ──────────────
  disputeRate:  { type: Number, default: 0 },   // disputes / transactions
  totalDisputes:{ type: Number, default: 0 },   // all-time
  fraudDisputes:{ type: Number, default: 0 },   // fraud-confirmed only

  // ── Volume analytics ──────────────────────────────────────
  totalTransactions: { type: Number, default: 0 },
  totalAmount:       { type: Number, default: 0 },
  uniqueCustomers:   { type: Number, default: 0 },
  flaggedTransactions: { type: Number, default: 0 },
  blockedTransactions: { type: Number, default: 0 },
  avgFraudScore:     { type: Number, default: 0 },
  maxFraudScore:     { type: Number, default: 0 },

  // ── Velocity / anomaly flags ──────────────────────────────
  velocityAnomaly: { type: Boolean, default: false },
  suddenSpike:     { type: Boolean, default: false },

  // ── Metadata ──────────────────────────────────────────────
  lastTransactionAt: { type: Date },
  status:      { type: String, enum: ['active', 'suspended', 'closed'], default: 'active' },
  notes:       [{ type: mongoose.Schema.Types.Mixed }],
}, {
  timestamps: true,
  optimisticConcurrency: true,
});

merchantSchema.index({ riskTier: 1, riskScore: -1 });
merchantSchema.index({ mcc: 1 });
merchantSchema.index({ disputeRate: -1 });

module.exports = mongoose.model('Merchant', merchantSchema);

// ── MCC lookup table (common Indian merchant categories) ──────
const MCC_CODES = {
  '5411': 'Grocery Stores / Supermarkets',
  '5412': 'Convenience Stores',
  '5422': 'Freezer & Locker Meat Provisioners',
  '5441': 'Candy, Nut, Confectionery Stores',
  '5451': 'Dairy Products Stores',
  '5462': 'Bakeries',
  '5499': 'Misc Food / Beverage',
  '5541': 'Gas Stations (with or without ancillary services)',
  '5542': 'Automated Fuel Dispensers',
  '5611': 'Men\'s & Boys\' Clothing',
  '5621': 'Women\'s Ready-to-Wear Stores',
  '5631': 'Women\'s Accessory & Specialty Stores',
  '5641': 'Children\'s & Infants\' Wear Stores',
  '5651': 'Family Clothing Stores',
  '5655': 'Sports & Riding Apparel Stores',
  '5661': 'Shoe Stores',
  '5691': 'Men\'s & Women\'s Clothing Stores',
  '5699': 'Misc Apparel & Accessory Stores',
  '5712': 'Furniture, Home Furnishings Stores',
  '5713': 'Floor Covering Stores',
  '5714': 'Drapery & Window Covering Stores',
  '5719': 'Misc Home Furnishing Stores',
  '5722': 'Household Appliance Stores',
  '5732': 'Electronic Stores',
  '5733': 'Music Stores / Instruments',
  '5734': 'Computer Software Stores',
  '5735': 'Record Stores',
  '5812': 'Eating Places / Restaurants',
  '5813': 'Drinking Places / Bars',
  '5814': 'Fast Food Restaurants',
  '5912': 'Drug Stores & Pharmacies',
  '5921': 'Package Stores / Liquor',
  '5931': 'Pawn Shops',
  '5932': 'Antique Reproductions',
  '5933': 'Pawnbrokers',
  '5941': 'Sporting Goods Stores',
  '5942': 'Book Stores',
  '5943': 'Stationery Stores',
  '5944': 'Jewelry Stores',
  '5945': 'Hobby / Toy / Game Shops',
  '5946': 'Camera & Photographic Supply Stores',
  '5947': 'Gift / Card / Novelty Stores',
  '5948': 'Luggage & Leather Goods Stores',
  '5949': 'Sewing / Needlework / Piece Goods',
  '5950': 'Glassware / Crystal Stores',
  '5970': 'Estate / Auto / Fire / Marine Insurance',
  '5972': 'Stamp / Coin Stores',
  '5973': 'Religious Goods Stores',
  '5975': 'Hearing Aids',
  '5976': 'Orthopedic Goods & Prosthetic Devices',
  '5977': 'Cosmetic Stores',
  '5978': 'Typewriter Stores',
  '5992': 'Florists',
  '5993': 'Cigar Stores & Stands',
  '5994': 'News Dealers / Newsstands',
  '5995': 'Pet Shops / Pet Food',
  '5996': 'Swimming Pools',
  '5997': 'Electric Razor Stores',
  '5998': 'Tent & Awning Shops',
  '5999': 'Misc Retail Stores',
  '6010': 'Financial Institutions — Manual Cash Disbursements',
  '6011': 'Financial Institutions — Automated Cash Disbursements (ATMs)',
  '6012': 'Financial Institutions — Merchandise & Services',
  '6051': 'Non-Financial Institutions — Foreign Currency',
  '6211': 'Security Brokers / Dealers',
  '6300': 'Insurance Underwriting',
  '7011': 'Lodging — Hotels / Motels / Resorts',
  '7012': 'Lodging — Timeshares',
  '7210': 'Laundry / Cleaning / Garment Services',
  '7211': 'Laundry Services',
  '7216': 'Dry Cleaners',
  '7217': 'Carpet & Upholstery Cleaning',
  '7221': 'Photographic Studios',
  '7230': 'Beauty & Barber Shops',
  '7251': 'Shoe Repair Shops',
  '7261': 'Funeral Services / Crematories',
  '7273': 'Dating / Escort Services',
  '7276': 'Tax Preparation Services',
  '7277': 'Debt / Marriage / Credit Counseling',
  '7278': 'Brokerage Services',
  '7296': 'Rental Leasing',
  '7297': 'Massage Parlors',
  '7298': 'Health & Beauty Spas',
  '7299': 'Misc Business Services',
  '7311': 'Advertising Services',
  '7321': 'Consumer Credit Reporting',
  '7333': 'Commercial Photography',
  '7338': 'Quick Copy / Reproduction',
  '7339': 'Stenographic / Secretarial Services',
  '7342': 'Exterminating / Disinfecting Services',
  '7349': 'Cleaning / Maintenance Services',
  '7361': 'Services — Commercial Printing',
  '7372': 'Services — Computer Programming',
  '7375': 'Information Retrieval Services',
  '7379': 'Services — Computer Repair',
  '7392': 'Management / Consulting Services',
  '7393': 'Detective / Protective / Security Services',
  '7394': 'Equipment & Tool Rental',
  '7395': 'Photo Developing',
  '7399': 'Services — Not Elsewhere Classified',
  '7512': 'Automobile Rental Agency',
  '7513': 'Truck & Utility Trailer Rentals',
  '7519': 'Motor Home / Recreational Vehicle Rentals',
  '7523': 'Parking Lots / Garages',
  '7534': 'Tire Related Services',
  '7535': 'Automotive Paint Shops',
  '7538': 'Automotive Service Shops',
  '7542': 'Car Washes',
  '7549': 'Towing Services',
  '7622': 'Air Conditioning & Refrigeration Repair',
  '7623': 'Agricultural Services',
  '7629': 'Electrical & Small Appliance Repair',
  '7631': 'Watch / Clock / Jewelry Repair',
  '7641': 'Furniture Repair / Refinishing',
  '7692': 'Welding Services',
  '7699': 'Services — Not Elsewhere Classified',
  '7800': 'Government-Owned Lottery',
  '7801': 'Government-Licensed Casinos',
  '7802': 'Government-Licensed Horse / Dog Racing',
  '7829': 'Government-Licensed Gambling',
  '7911': 'Dance Halls / Studios / Schools',
  '7922': 'Theatrical Producers / Ticket Agencies',
  '7929': 'Bands / Orchestras / Entertainers',
  '7932': 'Billiard / Pool Establishments',
  '7933': 'Bowling Alleys',
  '7941': 'Sports / Athletic Fields',
  '7991': 'Tourist Attractions / Exhibits',
  '7992': 'Golf Courses',
  '7993': 'Video Amusement Game Supplies',
  '7994': 'Video Game Arcades',
  '7995': 'Gambling / Betting Transactions',
  '7996': 'Amusement Parks / Circuses / Fortunes',
  '7997': 'Membership Clubs / Sports / Recreational',
  '7998': 'Aquariums / Dolphinariums / Planetariums',
  '7999': 'Misc Recreation Services',
  '8011': 'Services — Physicians',
  '8021': 'Services — Dentists',
  '8031': 'Services — Osteopaths',
  '8041': 'Services — Chiropractors',
  '8042': 'Services — Optometrists',
  '8043': 'Services — Ophthalmologists',
  '8049': 'Services — Podiatrists / Chiropodists',
  '8050': 'Services — Nursing / Personal Care',
  '8062': 'Services — Hospitals',
  '8071': 'Services — Medical & Dental Labs',
  '8099': 'Services — Health Practitioners NEC',
  '8111': 'Services — Legal Services / Attorneys',
  '8211': 'Services — Elementary / Secondary Schools',
  '8220': 'Services — Colleges / Universities',
  '8241': 'Services — Correspondence Schools',
  '8244': 'Services — Business / Secretarial Schools',
  '8249': 'Services — Vocational / Trade Schools',
  '8299': 'Services — Not Elsewhere Classified',
  '8351': 'Services — Child Care Services',
  '8398': 'Services — Charitable / Social Service Organizations',
  '8641': 'Services — Civic / Social / Fraternal Associations',
  '8651': 'Services — Political Organizations',
  '8661': 'Services — Religious Organizations',
  '8675': 'Services — Civic / Social / Fraternal Associations',
  '8698': 'Services — Membership Organizations NEC',
  '8734': 'Services — Testing Laboratories',
  '8911': 'Services — Architectural / Engineering / Surveying',
  '8931': 'Services — Accounting / Auditing / Bookkeeping',
  '8999': 'Services — Not Elsewhere Classified',
  '9211': 'Court Costs / Alimony / Child Support',
  '9222': 'Fines',
  '9223': 'Bail / Bond Payments',
  '9311': 'Tax Payments',
  '9399': 'Government Services NEC',
  '9401': 'Post Office — Postal Services Only',
  '9402': 'U.S. Federal Government Agencies',
};

module.exports.MCC_CODES = MCC_CODES;
